# Generated by Django 4.2 on 2024-09-21 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_rename_create_data_task_create_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='limit_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
