# Generated by Django 4.2 on 2024-09-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_task_limit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='limit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
