# Generated by Django 4.2 on 2024-09-21 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_alter_task_limit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_task',
            field=models.DateField(default=datetime.datetime(2024, 9, 21, 17, 8, 12, 939168, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
