# Generated by Django 4.2 on 2024-09-21 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_alter_task_create_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_task',
            field=models.DateField(default=datetime.datetime(2024, 9, 21, 17, 10, 15, 617588, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='limit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
