# Generated by Django 4.2 on 2024-09-21 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_alter_task_create_task_alter_task_limit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_task',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
