# Generated by Django 4.2 on 2024-09-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_alter_task_create_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='completation_date',
        ),
    ]
