# Generated by Django 4.2 on 2024-09-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_rename_due_date_task_completation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='limit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
