# Generated by Django 4.2 on 2024-09-23 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_alter_task_limit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='importance_task',
            name='importance_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='limit_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 9, 23)),
        ),
    ]
